apache_package_name: httpd
apache_service: httpd
php_package_name: php
mariadb_package_name: mariadb-server
samba_package_name: samba
ssh_users: "jay simone astrid"
ssh_template_file: sshd_config_centos.j2
test_file: test.txt.j2