apache_package_name: apache2
apache_service: apache2
php_package_name: libapache2-mod-php
mariadb_package_name: mariadb-server
samba_package_name: samba
ssh_users: " jay simone"
ssh_templates_files: sshd_config_ubuntu.j2
test_file: test.txt.j2