    - name: install mariadb packages (CentOS)
      tags: [centos, db, mariadb]
      dnf:
        name:
          - "{{apache_package_name}}"
          - "{{php_package_name}}"
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: [db, mariadb, ubuntu]
      apt:
        name:
          - "{{mariadb_package_name}}"
        state: latest
      when: ansible_distribution == "Ubuntu"