    - name: install unzip file
      package:
        name: unzip
        state: present

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.13.5/terraform_1.13.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: root
        group: root